/**
 * @file msgmap_eng.h
 * english resource message map
 */

	MESSAGE(STR_NOT_FOUND)

	/*** title ***/

	MESSAGE(DEBUG)
	MESSAGE(INFO)
	MESSAGE(INQUIRY)
	MESSAGE(WARN)
	MESSAGE(ERROR)
	MESSAGE(FATAL)
	MESSAGE(STRING)

	/*** generic ***/

	MESSAGE(MEW_LOAD_FAILED)
	MESSAGE(MEMALLOC_FAILED)
	MESSAGE(PROCESS_FAILED)
	MESSAGE(PROCESS_SUCCEED)
	MESSAGE(UNINSTALLING)
	MESSAGE(PROCESS_ABORTED)

	/* option */
	MESSAGE(OPTION_PARSE_FAILED)
	MESSAGE(UNKNOWN_OPTION)
	MESSAGE(OPTION_ARGMISSING)
	MESSAGE(OPTION_INVALID)
	MESSAGE(OPTION_MISSPARSER)
	MESSAGE(OPTION_USAGE)
	MESSAGE(OPTION_MOREINFO)

	/* rom file */
	MESSAGE(ROM_OPEN_FAILED)
	MESSAGE(ROM_IS_NOT_SMW)
	MESSAGE(ROM_WRITE_FAILED)

	/* asm file */
	MESSAGE(ASM_OPEN_FAILED)

	/* list file */
	MESSAGE(LIST_NOT_FOUND)
	MESSAGE(LIST_OPEN_FAILED)
	MESSAGE(LIST_PARSE_START)
	MESSAGE(LIST_PARSE_FAILED)
	MESSAGE(LIST_SYNTAX_ERROR)
	MESSAGE(LIST_INVALID_SECTION)
	MESSAGE(LIST_SECTION_MATCH)
	MESSAGE(LIST_INSERT_NUM_LARGE)
	MESSAGE(LIST_INSERT_NUM_FEW)
	MESSAGE(LIST_INSERT_CONFLICT)

	/* Uninstall */
	MESSAGE(UNINSTALL_NOT_INSTALLED)
	MESSAGE(UNINSTALL_RESADR_NULL)
	MESSAGE(UNINSTALL_DATA_BROKEN)
	MESSAGE(UNINSTALL_INVALID_RATS)
	MESSAGE(UNINSTALL_RATSCLEAN_NG)
	MESSAGE(UNINSTALL_PROCESS_GRP)
	MESSAGE(UNINSTALL_EXTENDED)
	MESSAGE(UNINSTALL_CLUSTER)
	MESSAGE(UNINSTALL_OVERWORLD)
	MESSAGE(UNINSTALL_SPRITES)
	MESSAGE(UNINSTALL_LIBRARIES)
	MESSAGE(UNINSTALL_COREDATA)
	MESSAGE(UNINSTALL_RESTORE)
	MESSAGE(UNINSTALL_CLEANING)
	MESSAGE(UNINSTALL_TWEAKING)
	MESSAGE(UNINSTALL_TWEAKS)
	MESSAGE(UNINSTALL_LEAKDATA)
	MESSAGE(UNINSTALL_NOTIMP_RES)

	/* Insert */
	MESSAGE(INSERT_PARSE_LIST)
	MESSAGE(INSERT_CREATE_WORKSP)
	MESSAGE(INSERT_COLLECT_LIBS)
	MESSAGE(INSERT_INITIALIZE_ROM)
	MESSAGE(INSERT_SPRITES)
	MESSAGE(INSERT_EXTENDED)
	MESSAGE(INSERT_CLUSTER)
	MESSAGE(INSERT_OVERWORLD)
	MESSAGE(INSERT_CLEAN_WORKSP)
	MESSAGE(INSERT_ASSEMBLE_ALL)
	MESSAGE(INSERT_CHK_DATA_LEAK)
	MESSAGE(INSERT_DATA_LEAK_DETECT)

	/* library */
	MESSAGE(LIBRARY_FOUND)
	MESSAGE(LIBRARY_CANT_OPEN)
	MESSAGE(LIBRARY_NOTHING)
	MESSAGE(LIBRARY_FILE_NUMBERS)
	MESSAGE(LIBRARY_LABEL_NUMBERS)

	/* assemble */
	MESSAGE(ASSEMBLE_FILE)
	MESSAGE(ASSEMBLE_FAILED)
	MESSAGE(ASSEMBLE_STR_WITH_ASMNAME)
	MESSAGE(ASSEMBLE_CFG_NOT_FOUND)
	MESSAGE(ASSEMBLE_EMPTY_ASM)
	MESSAGE(ASSEMBLE_USING_ASAR)
	MESSAGE(ASSEMBLE_USING_TRASM)
	MESSAGE(ASSEMBLE_ASM_NOT_FOUND)
	MESSAGE(ASSEMBLE_CFG_READ_ERROR)
	MESSAGE(ASSEMBLE_CFG_PROC_FAILED)
	MESSAGE(ASSEMBLE_BIN_OPEN_ERROR)
	MESSAGE(ASSEMBLE_PIPE_OPEN_ERROR)
	MESSAGE(ASSEMBLE_TRASM_ERR_COL)
	MESSAGE(ASSEMBLE_TRASM_LO_ONLY)
	MESSAGE(ASSEMBLE_ENTRY_NOT_FOUND)
	MESSAGE(ASSEMBLE_FREE_NOT_FOUND)

	/* parse cfg */
	MESSAGE(PARSECFG_FIELDS_TOO_FEW)
	MESSAGE(PARSECFG_READING_FILE)
	MESSAGE(PARSECFG_SYNTAX_ERROR)
	MESSAGE(PARSECFG_OLD_FORMAT_SP)
	MESSAGE(PARSECFG_OLD_FORMAT_SH)
	MESSAGE(PARSECFG_OLD_FORMAT_GEN)
	MESSAGE(PARSECFG_TAG_INVALID)

	/* extended / cluster */
	MESSAGE(EXTCLS_BROKEN_RELOC_ADR)
	MESSAGE(EXTCLS_EXTENDED_LOCATION)
	MESSAGE(EXTCLS_CLUSTER_LOCATION)

	/* sprites */
	MESSAGE(SPRITES_TWEAKS_LOC)
	MESSAGE(SPRITES_TABLE_GRP_LOC)

	/* initialize */
	MESSAGE(INITIALIZE_OLD_TOOL)
	MESSAGE(INITIALIZE_FORCE)
	MESSAGE(INITIALIZE_EXBYTE_QUES)
	MESSAGE(INITIALIZE_TERMED)
	MESSAGE(INITIALIZE_UPDATING)
	MESSAGE(INITIALIZE_UPDATE_NG)
	MESSAGE(INITIALIZE_INSTALLING)
	MESSAGE(INITIALIZE_VER_NOT_MATCH)
	MESSAGE(INITIALIZE_EXB_LMVER_SMALL)

	/* collect info */
	MESSAGE(COLLECT_LM_NOT_INSTALLED)
	MESSAGE(COLLECT_UNKNOWN_CHUNK)
	MESSAGE(COLLECT_LM_DOWNGRADED)
	MESSAGE(COLLECT_BROKEN_ROM)

	/* chkasm */
	MESSAGE(CHKASM_JUDGE_TRASM)
	MESSAGE(CHKASM_JUDGE_ASAR)
	MESSAGE(CHKASM_NON_COLON_TRASM)
	MESSAGE(CHKASM_COLON_ASAR)

	/* exbytes */
	MESSAGE(EXBYTES_SPR_DATA_REMAP)
	MESSAGE(EXBYTES_INVALID_ADDR)
	MESSAGE(EXBYTES_SPRTERM_NOT_FOUND)

	/* ramen */
	MESSAGE(RAMEN_END)
	MESSAGE(RAMEN_END_TITLE)

#if defined(GUI) && isWindows

	/*--- Menu ---*/
	/* File */
	MESSAGE(MENU_FILE)
	MESSAGE(MENU_FILE_INSERT)
	MESSAGE(MENU_FILE_UNINSTALL)
	MESSAGE(MENU_FILE_ABORT)
	MESSAGE(MENU_FILE_EXIT)

	/* Option */
	MESSAGE(MENU_OPTION)
	MESSAGE(MENU_OPTION_PIXI)
	MESSAGE(MENU_OPTION_EBEN)
	MESSAGE(MENU_OPTION_FORCE)
	MESSAGE(MENU_OPTION_DEBUG)
	MESSAGE(MENU_OPTION_WARN)
	MESSAGE(MENU_OPTION_DIR)
	MESSAGE(MENU_OPTION_SSC)

	/* Help */
	MESSAGE(MENU_HELP)
	MESSAGE(MENU_HELP_VERSION)

	/* Main Window */
	MESSAGE(MAINWND_ROM_FILE)
	MESSAGE(MAINWND_LIST_FILE)
	MESSAGE(MAINWND_DEFINES)
	MESSAGE(MAINWND_INSERT)

	/* OpenFileDialog filter */
	MESSAGE(OFNFILTER_ROM_FILE)
	MESSAGE(OFNFILTER_LIST_FILE)
	MESSAGE(OFNFILTER_DEFAULT_ROM)
	MESSAGE(OFNFILTER_DEFAULT_LIST)

	/* ListView */
	MESSAGE(LISTVIEW_COL_NAME)
	MESSAGE(LISTVIEW_COL_VALUE)

	/* Common button */
	MESSAGE(BUTTON_OK)
	MESSAGE(BUTTON_CANCEL)
	MESSAGE(BUTTON_LOAD)
	MESSAGE(BUTTON_SAVE)

	/* Directory Option Dialog */
	MESSAGE(DIROPTDLG)
	MESSAGE(DIROPTDLG_LIBRARIES)
	MESSAGE(DIROPTDLG_SPRITES)
	MESSAGE(DIROPTDLG_EXTENDEDES)
	MESSAGE(DIROPTDLG_CLUSTERS)
	MESSAGE(DIROPTDLG_ERREMPTY)

	/* Information Dialog */
	MESSAGE(INFDLG)
	MESSAGE(INFDLG_VERSION)
	MESSAGE(INFDLG_VER_DESC)
	MESSAGE(INFDLG_DEBUG)
	MESSAGE(INFDLG_WARNING)
	MESSAGE(INFDLG_WARNING_DESC)
	MESSAGE(INFDLG_ERROR)
	MESSAGE(INFDLG_ERROR_DESC)

	/* Information Dialog Tabs */
	MESSAGE(INFDLG_TAB_LIBS)
	MESSAGE(INFDLG_TAB_DEBUG)
	MESSAGE(INFDLG_TAB_WARNING)
	MESSAGE(INFDLG_TAB_ERROR)
	MESSAGE(INFDLG_TAB_FATAL)

	/* Status bar */
	MESSAGE(STSBAR_READY)
	MESSAGE(STSBAR_PROGRESS)

	/* input error */
	MESSAGE(INPUTERR_EMPTY)
	MESSAGE(INPUTERR_DUPKEY)

	/* Ini file error */
	MESSAGE(INI_LOAD_FAILED)
	MESSAGE(INI_SAVE_FAILED)

	/* Tooltip warnings */
	MESSAGE(TOOLTIP_OPEN_FAILED)

#endif

