/**
 * @file msgmap_jp.h
 * japanese resource message map
 */

	MESSAGE(JP_STR_NOT_FOUND)

	/*** title ***/

	MESSAGE(JP_DEBUG)
	MESSAGE(JP_INFO)
	MESSAGE(JP_INQUIRY)
	MESSAGE(JP_WARN)
	MESSAGE(JP_ERROR)
	MESSAGE(JP_FATAL)
	MESSAGE(JP_STRING)

	/*** generic ***/

	MESSAGE(JP_MEW_LOAD_FAILED)
	MESSAGE(JP_MEMALLOC_FAILED)
	MESSAGE(JP_PROCESS_FAILED)
	MESSAGE(JP_PROCESS_SUCCEED)
	MESSAGE(JP_UNINSTALLING)
	MESSAGE(JP_PROCESS_ABORTED)

	/* option */
	MESSAGE(JP_OPTION_PARSE_FAILED)
	MESSAGE(JP_UNKNOWN_OPTION)
	MESSAGE(JP_OPTION_ARGMISSING)
	MESSAGE(JP_OPTION_INVALID)
	MESSAGE(JP_OPTION_MISSPARSER)
	MESSAGE(JP_OPTION_USAGE)
	MESSAGE(JP_OPTION_MOREINFO)

	/* rom file */
	MESSAGE(JP_ROM_OPEN_FAILED)
	MESSAGE(JP_ROM_IS_NOT_SMW)
	MESSAGE(JP_ROM_WRITE_FAILED)

	/* asm file */
	MESSAGE(JP_ASM_OPEN_FAILED)

	/* list file */
	MESSAGE(JP_LIST_NOT_FOUND)
	MESSAGE(JP_LIST_OPEN_FAILED)
	MESSAGE(JP_LIST_PARSE_START)
	MESSAGE(JP_LIST_PARSE_FAILED)
	MESSAGE(JP_LIST_SYNTAX_ERROR)
	MESSAGE(JP_LIST_INVALID_SECTION)
	MESSAGE(JP_LIST_SECTION_MATCH)
	MESSAGE(JP_LIST_INSERT_NUM_LARGE)
	MESSAGE(JP_LIST_INSERT_NUM_FEW)
	MESSAGE(JP_LIST_INSERT_CONFLICT)

	/* Uninstall */
	MESSAGE(JP_UNINSTALL_NOT_INSTALLED)
	MESSAGE(JP_UNINSTALL_RESADR_NULL)
	MESSAGE(JP_UNINSTALL_DATA_BROKEN)
	MESSAGE(JP_UNINSTALL_INVALID_RATS)
	MESSAGE(JP_UNINSTALL_RATSCLEAN_NG)
	MESSAGE(JP_UNINSTALL_PROCESS_GRP)
	MESSAGE(JP_UNINSTALL_EXTENDED)
	MESSAGE(JP_UNINSTALL_CLUSTER)
	MESSAGE(JP_UNINSTALL_OVERWORLD)
	MESSAGE(JP_UNINSTALL_SPRITES)
	MESSAGE(JP_UNINSTALL_LIBRARIES)
	MESSAGE(JP_UNINSTALL_COREDATA)
	MESSAGE(JP_UNINSTALL_RESTORE)
	MESSAGE(JP_UNINSTALL_CLEANING)
	MESSAGE(JP_UNINSTALL_TWEAKING)
	MESSAGE(JP_UNINSTALL_TWEAKS)
	MESSAGE(JP_UNINSTALL_LEAKDATA)
	MESSAGE(JP_UNINSTALL_NOTIMP_RES)

	/* Insert */
	MESSAGE(JP_INSERT_PARSE_LIST)
	MESSAGE(JP_INSERT_CREATE_WORKSP)
	MESSAGE(JP_INSERT_COLLECT_LIBS)
	MESSAGE(JP_INSERT_INITIALIZE_ROM)
	MESSAGE(JP_INSERT_SPRITES)
	MESSAGE(JP_INSERT_EXTENDED)
	MESSAGE(JP_INSERT_CLUSTER)
	MESSAGE(JP_INSERT_OVERWORLD)
	MESSAGE(JP_INSERT_CLEAN_WORKSP)
	MESSAGE(JP_INSERT_ASSEMBLE_ALL)
	MESSAGE(JP_INSERT_CHK_DATA_LEAK)
	MESSAGE(JP_INSERT_DATA_LEAK_DETECT)

	/* library */
	MESSAGE(JP_LIBRARY_FOUND)
	MESSAGE(JP_LIBRARY_CANT_OPEN)
	MESSAGE(JP_LIBRARY_NOTHING)
	MESSAGE(JP_LIBRARY_FILE_NUMBERS)
	MESSAGE(JP_LIBRARY_LABEL_NUMBERS)

	/* assemble */
	MESSAGE(JP_ASSEMBLE_FILE)
	MESSAGE(JP_ASSEMBLE_FAILED)
	MESSAGE(JP_ASSEMBLE_STR_WITH_ASMNAME)
	MESSAGE(JP_ASSEMBLE_CFG_NOT_FOUND)
	MESSAGE(JP_ASSEMBLE_EMPTY_ASM)
	MESSAGE(JP_ASSEMBLE_USING_ASAR)
	MESSAGE(JP_ASSEMBLE_USING_TRASM)
	MESSAGE(JP_ASSEMBLE_ASM_NOT_FOUND)
	MESSAGE(JP_ASSEMBLE_CFG_READ_ERROR)
	MESSAGE(JP_ASSEMBLE_CFG_PROC_FAILED)
	MESSAGE(JP_ASSEMBLE_BIN_OPEN_ERROR)
	MESSAGE(JP_ASSEMBLE_PIPE_OPEN_ERROR)
	MESSAGE(JP_ASSEMBLE_TRASM_ERR_COL)
	MESSAGE(JP_ASSEMBLE_TRASM_LO_ONLY)
	MESSAGE(JP_ASSEMBLE_ENTRY_NOT_FOUND)
	MESSAGE(JP_ASSEMBLE_FREE_NOT_FOUND)

	/* parse cfg */
	MESSAGE(JP_PARSECFG_FIELDS_TOO_FEW)
	MESSAGE(JP_PARSECFG_READING_FILE)
	MESSAGE(JP_PARSECFG_SYNTAX_ERROR)
	MESSAGE(JP_PARSECFG_OLD_FORMAT_SP)
	MESSAGE(JP_PARSECFG_OLD_FORMAT_SH)
	MESSAGE(JP_PARSECFG_OLD_FORMAT_GEN)

	/* extended / cluster */
	MESSAGE(JP_EXTCLS_BROKEN_RELOC_ADR)
	MESSAGE(JP_EXTCLS_EXTENDED_LOCATION)
	MESSAGE(JP_EXTCLS_CLUSTER_LOCATION)

	/* sprites */
	MESSAGE(JP_SPRITES_TWEAKS_LOC)
	MESSAGE(JP_SPRITES_TABLE_GRP_LOC)

	/* initialize */
	MESSAGE(JP_INITIALIZE_OLD_TOOL)
	MESSAGE(JP_INITIALIZE_FORCE)
	MESSAGE(JP_INITIALIZE_EXBYTE_QUES)
	MESSAGE(JP_INITIALIZE_TERMED)
	MESSAGE(JP_INITIALIZE_UPDATING)
	MESSAGE(JP_INITIALIZE_UPDATE_NG)
	MESSAGE(JP_INITIALIZE_INSTALLING)
	MESSAGE(JP_INITIALIZE_VER_NOT_MATCH)
	MESSAGE(JP_INITIALIZE_EXB_LMVER_SMALL)

	/* collect info */
	MESSAGE(JP_COLLECT_LM_NOT_INSTALLED)
	MESSAGE(JP_COLLECT_UNKNOWN_CHUNK)
	MESSAGE(JP_COLLECT_LM_DOWNGRADED)
	MESSAGE(JP_COLLECT_BROKEN_ROM)

	/* chkasm */
	MESSAGE(JP_CHKASM_JUDGE_TRASM)
	MESSAGE(JP_CHKASM_JUDGE_ASAR)
	MESSAGE(JP_CHKASM_NON_COLON_TRASM)
	MESSAGE(JP_CHKASM_COLON_ASAR)

	/* exbytes */
	MESSAGE(JP_EXBYTES_SPR_DATA_REMAP)
	MESSAGE(JP_EXBYTES_INVALID_ADDR)
	MESSAGE(JP_EXBYTES_SPRTERM_NOT_FOUND)

	/* ramen */
	MESSAGE(JP_RAMEN_END)
	MESSAGE(JP_RAMEN_END_TITLE)

#if defined(GUI) && isWindows

	/*--- Menu ---*/
	/* File */
	MESSAGE(JP_MENU_FILE)
	MESSAGE(JP_MENU_FILE_INSERT)
	MESSAGE(JP_MENU_FILE_UNINSTALL)
	MESSAGE(JP_MENU_FILE_ABORT)
	MESSAGE(JP_MENU_FILE_EXIT)

	/* Option */
	MESSAGE(JP_MENU_OPTION)
	MESSAGE(JP_MENU_OPTION_PIXI)
	MESSAGE(JP_MENU_OPTION_EBEN)
	MESSAGE(JP_MENU_OPTION_FORCE)
	MESSAGE(JP_MENU_OPTION_DEBUG)
	MESSAGE(JP_MENU_OPTION_WARN)
	MESSAGE(JP_MENU_OPTION_DIR)

	/* Help */
	MESSAGE(JP_MENU_HELP)
	MESSAGE(JP_MENU_HELP_VERSION)

	/* Main Window */
	MESSAGE(JP_MAINWND_ROM_FILE)
	MESSAGE(JP_MAINWND_LIST_FILE)
	MESSAGE(JP_MAINWND_DEFINES)
	MESSAGE(JP_MAINWND_INSERT)

	/* OpenFileDialog filter */
	MESSAGE(JP_OFNFILTER_ROM_FILE)
	MESSAGE(JP_OFNFILTER_LIST_FILE)
	MESSAGE(JP_OFNFILTER_DEFAULT_ROM)
	MESSAGE(JP_OFNFILTER_DEFAULT_LIST)

	/* ListView */
	MESSAGE(JP_LISTVIEW_COL_NAME)
	MESSAGE(JP_LISTVIEW_COL_VALUE)

	/* Common button */
	MESSAGE(JP_BUTTON_OK)
	MESSAGE(JP_BUTTON_CANCEL)
	MESSAGE(JP_BUTTON_LOAD)
	MESSAGE(JP_BUTTON_SAVE)

	/* Directory Option Dialog */
	MESSAGE(JP_DIROPTDLG)
	MESSAGE(JP_DIROPTDLG_LIBRARIES)
	MESSAGE(JP_DIROPTDLG_SPRITES)
	MESSAGE(JP_DIROPTDLG_EXTENDEDES)
	MESSAGE(JP_DIROPTDLG_CLUSTERS)
	MESSAGE(JP_DIROPTDLG_ERREMPTY)

	/* Information Dialog */
	MESSAGE(JP_INFDLG)
	MESSAGE(JP_INFDLG_VERSION)
	MESSAGE(JP_INFDLG_VER_DESC)
	MESSAGE(JP_INFDLG_DEBUG)
	MESSAGE(JP_INFDLG_WARNING)
	MESSAGE(JP_INFDLG_WARNING_DESC)
	MESSAGE(JP_INFDLG_ERROR)
	MESSAGE(JP_INFDLG_ERROR_DESC)

	/* Information Dialog Tabs */
	MESSAGE(JP_INFDLG_TAB_LIBS)
	MESSAGE(JP_INFDLG_TAB_DEBUG)
	MESSAGE(JP_INFDLG_TAB_WARNING)
	MESSAGE(JP_INFDLG_TAB_ERROR)
	MESSAGE(JP_INFDLG_TAB_FATAL)

	/* Status bar */
	MESSAGE(JP_STSBAR_READY)
	MESSAGE(JP_STSBAR_PROGRESS)

#endif

